silent_shutdown: False

login:
    # limit: 10
    batch_size: 20
    log: True
    remove_proxy_on_error: False

    attempts:
        log: False
        batch_size: 15

    connection:
        limit_per_host: 0
        timeout: 5
        limit: 200

proxies:

    pool:
        timeout: 25
        prepopulate: True
        collect: True
        log: False

        max_resp_time: 5.0
        max_connection_errors: 2
        max_error_rate: 0.5
        max_req_proxy: 10
        min_time_between_proxy: 10

    broker:
        max_conn: 200
        max_tries: 2
        timeout: 5
        log: False
        # limit: 2000
