log:
    proxies: False
    attempts: False
    login: True

login:
    password_limit: 10
    batch_size: 20
    attempt_batch_size: 10

    connection:
        limit_per_host: 0
        timeout: 5
        limit: 200

    proxies:
        prepopulate: True
        collect: False
        # limit: 2000
        # prepopulate_limit: 10000

        pool:
            max_resp_time: 6
            max_error_rate: 0.5
            min_req_proxy: 6
            timeout: 25

        broker:
            max_conn: 200
            max_tries: 2
            timeout: 5
