log:
    operator: "DEBUG"
    proxy_broker: "DEBUG"
    login_attempts: "DEBUG"
    proxy_pool: "DEBUG"

login:
    # limit: 100
    batch_size: 20

    attempts:
        batch_size: 15

    connection:
        limit_per_host: 0
        timeout: 10
        limit: 200

proxies:
    collect: False
    prepopulate: True
    pool:
        # The maximum amount of time to wait for a proxy from the queue before failing.
        timeout: 25
        # The maximum response time in seconds. If proxy.avg_resp_time exceeds this
        # value, proxy will be removed from the pool.
        max_resp_time: 5.0
        # The maximum number of allowed connection errors for a proxy before being
        # removed from the pool.
        max_connection_errors: 2
        # The maximum overall error rate for a proxy to be put into or used from
        # the pool.
        max_error_rate: 0.5
        # The minimum number of requests that a proxy can be used for (overall/saved)
        # before the error_rate starts becoming a factor.
        error_rate_horizon: 5
        # The maxmium number of allowed requests for each proxy per attack, before
        # being removed from pool.
        max_requests: 10
        # The amount of time to wait before using a proxy that raises a 429 too many
        # requests error.
        time_between_request_timeout: 10
        remove_proxy_on_error: False

    # Settings Here Only Matter if Collect = True
    broker:
        # The maximum number of concurrent checks of proxies
        max_conn: 200
        # The maximum number of attempts to check a proxy
        # Note that the lower the value of max_tries, the faster the broker will return
        # proxies, but they will not contain as much information to gauge their
        # relative reliability and speed.
        max_tries: 2

        # Maximum amount of time to wait for broker to return a proxy before failing.
        timeout: 5

        # Not sure if we are going to allow a limit parameter yet.
        # limit: 2000
