silent_shutdown: False

login:
    # limit: 10
    batch_size: 10
    log: True
    remove_proxy_on_error: True

    attempts:
        log: True
        batch_size: 5

    connection:
        limit_per_host: 0
        timeout: 5
        limit: 200

proxies:

    pool:
        timeout: 25
        prepopulate: True
        collect: True
        log: False

        max_resp_time:
            value: 4.0
            strict: False

        max_error_rate:
            value: 0.5
            strict: True

        min_req_proxy:
            value: 6
            strict: False

    broker:
        max_conn: 200
        max_tries: 2
        timeout: 5
        log: False
        # limit: 2000
